<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
	  <LangVersion>latest</LangVersion>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ChartGenerator.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Plotly.NET" Version="5.1.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="9.0.202" />
  </ItemGroup>

</Project>
